config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates :comment, presence: true

end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    has_many :comments

    validates :name, presence: true
    validates :handle, presence: true, uniqueness: { case_sensitive: false }
    validates :description, presence: true, length: { minimum: 20 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def index
        @comments = Comment.all
    end
    
    def new
        @comment = Comment.new
    end
    
    def show
        @comment = Comment.find(params[:id])
    end
    
    def create
        comment = Comment.create!(comment_params)
        if comment.valid?
            comment.save
            redirect_to comments_path
        else
            flash[:errors] = comment.errors.full_messages
            redirect_to new_comment_path
        end
    end
    
    def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to comments_path
    end
    
    private
    
    def comment_params
    params.require(:comment).permit(:comment, :user_id, :post_id)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = Post.all
    end
    
    def new
        @post = Post.new
    end
    
    def show
        @post = Post.find(params[:id])
        @user = User.all
        @comment = Comment.all
    end
    
    def create
        Post.create!(post_params)
        redirect_to posts_path
        
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
        post = Post.find(params[:id])
        post.update(post_params)
        redirect_to american
    end
    
    def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to posts_path
    
    end
  
    private
    
    def post_params
        params.require(:post).permit(:title, :user_id, :item, :comment)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
    @users = User.all 
end

def new
    @user = User.new
end

def show
    @user = User.find(params[:id])
    @post = Post.all
end

def create
    user = User.create(user_params)
    if user.valid?
        user.save
    redirect_to users_path
    else
        flash[:errors] = user.errors.full_messages
        redirect_to new_user_path
    end
end

def edit
    @user = User.find(params[:id])
end

def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user

end

def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
end

private

def user_params
    params.require(:user).permit(:name, :handle, :description)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.erb
<h2>Below are all comments with there associated user!</h2>

<% @comments.each do |user_comment| %>
<p><%= link_to user_comment.comment, user_comment %></p>
<% end %>

app/views/comments/new.erb
<h2> What do you want to say? </h2>

<%= form_with model: @comment do |f|%>
<%= f.collection_select :user_id, User.all, :id, :name, prompt: true %>
<%= f.collection_select :post_id, Post.all, :id, :title, prompt: true %>
<%= f.text_field :comment, placeholder: 'Comment' %>
<%= f.submit %>
<% end %>

app/views/comments/show.erb
<%= link_to "Back to user comments", comments_path %>

<h2><%= @comment.comment %></h2>

<%= button_to "Delete comment", @comment, :method=>:delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>



<html>
  <head>
    <title>WWYDApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <br> <div><%= link_to "Home", users_path %> &nbsp;&nbsp;&nbsp;

  <%= link_to "Lists", posts_path %> &nbsp;&nbsp;&nbsp;

  <%= link_to "Create New List", new_post_path %> &nbsp;&nbsp;&nbsp;

  <%= link_to "Create Comment", new_comment_path %></div> </br>

    <%= yield %>
  </body>
</html>

app/views/posts/edit.erb
<h1>Edit the current post below!</h1>


<%= form_with model: @post do |f| %>
<%= f.text_field :title, placeholder: 'Title' %>
<%= f.number_field :user_id, min: 47 , placeholder: 'User' %>
<%= f.text_field :item, placeholder: 'Item' %>
<%= f.text_field :comment, placeholder: 'Comment' %>
<%= f.submit %>
<% end %>

app/views/posts/index.erb
<h1>WWYD To-Do Lists</h1>

<% @posts.each do |post| %>
<p><%= link_to post.title, post %></p>
<% end %>

app/views/posts/new.erb
<h1>Create a new list, below!</h1>

<%= form_with model: @post do |f| %>
<%= f.text_field :title, placeholder: 'Title' %>
<%= f.collection_select :user_id, User.all, :id, :name, prompt: true %>
<%= f.text_field :item, placeholder: 'Item' %>
<%= f.text_field :comment, placeholder: 'Comment' %>
<%= f.submit %>
<% end %>

app/views/posts/show.erb
<div><font size = "6">Title: <%= @post.title %></font>
<%= button_to "Delete this post", @post, :method => :delete %></div>


<p>User: <% @user.each do |i| %>
         <% if  i.id == @post.user_id %>
        <%= i.name %>
        <% end %>
    <% end %>
</p>
<p>Item: <%= @post.item %></p>
<p>Description: <%= @post.comment %></p>

<p> <% @comment.each do |c| %>
         <% if  c.user_id == @post.user_id %>
        <%= c.comment%>
<br/>   
      
        <% end %>
        
    <% end %>
</p>



<%= link_to "Return to Posts", posts_path %>

app/views/users/edit.erb
<h2>Make any desired changes to your personal description below!</h2>

<%= form_with model: @user do |f| %>
<%= f.text_field :description, placeholder: 'Description' %>
<%= f.submit %>
<% end %>

app/views/users/index.erb
<h1>Welcome to the WWYD To-Do List</h1>
<h2>A social To-Do List</h2>

<% @users.each do |user| %>
<p><%= link_to user.name, user %></p>
<% end %>

<h3><%= link_to "Create a new user", new_user_path %></h3>

app/views/users/new.erb
<h2>Please enter you information to create a new account below!</h2>

<% if flash[:errors]%>
    <% flash[:errors].each do |error| %>
        <p style="color:red"><%= error %></p>
        <% end %>
    <% end %>

<%= form_with model: @user do |f| %>
<%= f.text_field :name, placeholder: 'Name' %>
<%= f.text_field :handle, placeholder: 'Handle' %>
<%= f.text_field :description, placeholder: 'Description' %>
<%= f.submit %>
<% end %>

<h4><%= link_to "Return to WWYD", users_path %></h4>

app/views/users/show.erb
<div>Name: <%= @user.name %>
<%= button_to "Delete User", @user, :method=>:delete %></div>
<p>Username: <%= @user.handle %></p>
<div>Description: <%= @user.description %>  <%= link_to "Edit Description", edit_user_path %>


</div>